### ISSUE TITLE
Do you know hot decrypt the draft file in the latest release version，especially the encrypt video?

### ISSUE THREAD

**Issue by HTWMedia** [emosheeep/capcut-export#1]
Do you know hot decrypt the draft file in the latest release version，especially the encrypt video?

**Comment by emosheeep** [comment]
I don't know yet, otherwise I'll do some updates to make it work.

**Comment by philljones22** [comment]
[CapCut trending templates](https://capctemplates.com/) showcase the latest styles and effects that are popular among creators, making it easy to elevate your video content. With these templates, you can stay current and engage your audience with fresh, eye-catching visuals that stand out.

**Comment by Emmasnow0022** [comment]
Want to know the real worth of the stars? NetWorthExactly has accurate net worth figures on your favorite personalities. To explore more about networth of different personalities visit: https://networthexactly.com/

**Comment by emosheeep** [comment]
Uh？What did you say?
